### PR TITLE
Improve query building.

### PR DESCRIPTION
**Pull request by charphi**
This PR adds a rest query builder that simplifies coding by avoiding string concatenation in queries.

### CODE REVIEW

**Comment by vpinna80** [comment]
Thank you, Philippe.
We'll be reviewing the code and then be back to you.

**Comment by vpinna80** [comment]
I've added some modifications to your code waiting for Attilio to oversee all the changes.

**Comment by charphi** [comment]
Just a few remarks:

The property `needsURLEncoding` is no more used in your changes.
Is this property still relevant ? Are there servers that would fail if you send encoded stuff ?

`RestQueryBuilder` encodes only key parts of parameters. It should also encode value parts and path elements.

From a design point of view, I would favor composition over inheritance. 
For example, `Sdmx21Queries` vs `RestQueryBuilder`.

**Comment by vpinna80** [comment]
The `needsUrlEncoding` configuration property is obsolete by now, but we're keeping it since it is on the public API; the intention is to completely remove it from a future release, and have all URLs encoded by default.

For the second part you're right, and i just made a little patch to fix it, though there's not yet a case in which it is relevant.

For the last part, both approaches have pros and cons, and in the end it's just a matter of personal preference; in this particular case I switched to inheritance because it made easier to remove static methods with side effects (compare [`addResourceId`](https://github.com/charphi/SDMX/blob/7141cb604ed5c23741c8e5d1f46f5662acec0a50/JAVA/src/it/bancaditalia/oss/sdmx/parser/v21/Sdmx21Queries.java#L96) and [`addParams`](https://github.com/charphi/SDMX/blob/7141cb604ed5c23741c8e5d1f46f5662acec0a50/JAVA/src/it/bancaditalia/oss/sdmx/parser/v21/Sdmx21Queries.java#L107)). But those could have been translated to instance forwarding methods just as well.

**Pull request merged**
