### PR TITLE
jitpack binaries are broken

### PR DESCRIPTION
**Pull request by charphi**
The binaries generated by jitpack are currently broken.
This is due to a reference to a non-existing parent-pom:
```xml
 <parent>
    <groupId>it.bancaditalia.oss</groupId>
    <artifactId>parent-pom</artifactId>
    <version>1.0.0</version>
    <relativePath>../parent-pom.xml</relativePath>
  </parent>
  <groupId>com.github.amattioc</groupId>
  <artifactId>SDMX</artifactId>
  <version>798fc8609f</version>
```

I use jitpack to reference a library not-yet-released in maven central. That is quite useful because it allows me to use new features as soon as possible without waiting the next release. (see #98)

I've removed the parent-pom to solve the problem. I'm not sure of the purpose of it so I hope it doesn't break anything else.

### CODE REVIEW

**Comment by charphi** [comment]
For the parent-pom, I guess there are other projects not hosted here that uses it?

For jitpack. I'm not sure to get it right since jitpack does not really need STATA sources and moreover it can be complementary to maven central.

**Comment by charphi** [comment]
I've just checked and it seems that the binaries on maven central are also broken.
If I add a single reference to `it.bancaditalia.oss:sdmx:2.0.4`, maven complains that it could not find the artifact `it.bancaditalia.oss:parent-pom:pom:1.0.0`

```xml
<dependencies>
	<dependency>
		<groupId>it.bancaditalia.oss</groupId>
		<artifactId>sdmx</artifactId>
		<version>2.0.4</version>
	</dependency>
</dependencies>
```

`Failed to execute goal on project mavenproject1: Could not resolve dependencies for project com.mycompany:mavenproject1:jar:1.0-SNAPSHOT: Failed to collect dependencies for [it.bancaditalia.oss:sdmx:jar:2.0.4 (compile)]: Failed to read artifact descriptor for it.bancaditalia.oss:sdmx:jar:2.0.4: Could not find artifact it.bancaditalia.oss:parent-pom:pom:1.0.0 in central (http://repo.maven.apache.org/maven2) -> [Help 1]`

**Comment by vpinna80** [comment]
A fix for parent-pom.xml will come in the next release.
In the mean time you can issue this command as a workaround:
`mvn -f parent-pom.xml install`
It will install the parent pom in your local repository so that maven will not complain about not finding it.

**Comment by charphi** [comment]
Thanks for the tip.
Still, this manual intervention breaks the continuous integration checks (TravisCI) and breaks all automation around it.

**Comment by charphi** [comment]
Binaries on maven central still broken with 2.0.5 (4faccdd66df4165f03af2a909828e1e2919d0b78)

**Comment by vpinna80** [comment]
@charphi Are your integration issues resolved with the [latest version](https://github.com/amattioc/SDMX/commit/2faac6d7642f540c42f61888351733f55fda124b)?

**Comment by amattioc** [comment]
Hi @charphi any news on the integration issue?

**Comment by charphi** [comment]
I still have the same problem: while `sdmx` artifact is present on Maven Central, `sdmx-parent` is not.

**Comment by vpinna80** [comment]
I have released the parent pom on Nexus; this will take a couple of hours but it should fix the problem.
However it is (way) better if you install the parent pom yourself, by placing it inside your project and adding the installation step into the .yml file.

**Pull request closed without merging**
