### PR TITLE
Several fixes for INEGI client.

### PR DESCRIPTION
**Pull request by charphi**
The data structure returned by the INEGI client is incomplete:
- references=children is missing
- agencyId is null in some cases

Call example :
http://www.snieg.mx/opendata/NSIRestService/DataStructure/OECD/KF_STES/ALL?references=children

### CODE REVIEW

**Comment by amattioc** [comment]
Thanks for that. 
The changes will not have an impact on the SDMXClientHandler users (e.g. all stats tools and sdmx helper), because the handler will continue doing a "lazy loading" by calling the single codelist API. Anyway I remember you're using the clients individually.

Best, Attilio

**Comment by charphi** [comment]
You are welcome :)
The problem was also linked to a specific node of sdmx-ml (ConceptScheme) which somehow gives its attributes to its children concepts. So, it might also be useful for future endpoints.

**Comment by amattioc** [comment]
Hi @charphi, I just added a reference to jdemetra-dotstat in the readme of the connectors. Nice project.

Best, Attilio

**Comment by charphi** [comment]
Thank you

**Pull request merged**
