### PR TITLE
Fixed missing codelist values in ILO client.

### PR DESCRIPTION
**Pull request by charphi**
ILO client doesn't query values of codelists when getting DSD.

By the way, according to its documentation, it seems that ILO follows part of SDMX v2.1 spec.
It could be usefull to refactor the client to use it.
http://www.ilo.org/ilostat/content/conn/ILOSTATContentServer/path/Contribution%20Folders/statistics/web_pages/static_pages/technical_page/ilostat_appl/SDMX_User_Guide.pdf

### CODE REVIEW

**Comment by amattioc** [comment]
Hi @charphi 
for providers that offer an explicit 'getcodes' API (i.e all 2.1 ones and ILO) I preferred to delay the loading of codes as this can take some time and keep the user waiting for something that he may not need. 
Is this behaviour not suitable for your application? 

Best, Attilio

**Comment by charphi** [comment]
Indeed, I need the codes.
But, it might not be a problem since you can request it (or not) through the use of "full" parameter.

**Comment by amattioc** [comment]
I could add a configuration parameter (and a method in the Configuration class) that selects the behaviour to this regard. Would it help?

**Comment by charphi** [comment]
As I understand it, the second parameter of the following method determines if the returned datastructure contains all dimensions and codelists:
`GenericSDMXClient#getDataFlowStructure(DSDIdentifier,boolean)`

So, if you don't need codes, you just have to pass `false` to the parameter.

Is there a third possibility where one needs part of it, like dimensions without codes?

**Comment by amattioc** [comment]
Hi, that's correct. The boolean parameter decides if you add the **references=children** parameter in the http request (see `RestQueryBuilder#getStructureQuery`). The parser will then take into account all the response, as it arrives.

I'm not sure I understood what you mean about the third possibility: the dimensions are already in the minimal structure response. If you request the children you will then have the codes for each dimension. As an example, look at the response for these queries:

http://www.ilo.org/ilostat/sdmx/ws/rest/datastructure/ILO/MIG_ALL_EMP_TEMP_SEX_AGE_MIG_NB?references=children

http://www.ilo.org/ilostat/sdmx/ws/rest/datastructure/ILO/MIG_ALL_EMP_TEMP_SEX_AGE_MIG_NB

What may be misleading is that some providers (most non 2.1 ones) add the children regardless the references parameter.

**Comment by amattioc** [comment]
Hi @charphi 

I realized that there was some mess in the hierarchy of the datastructure URL builders and I fixed it in 7ae7de3702cb9aaec298c2b24b0a8c0eb338af83 . Can you check if this clears your issue? (you will still need to use the full=true parameter anyway)

**Comment by charphi** [comment]
I just checked and this is working properly now.
Thanks.

**Pull request closed without merging**
