### PR TITLE
Added ssl&proxy properties to RestSdmxClient.

### PR DESCRIPTION
**Pull request by charphi**
These properties are used to programmatically customize how a client access a web service.

### CODE REVIEW

**Comment by amattioc** [comment]
Hi @charphi , thanks for the PR.

Could you explain briefly what would be the benefits of having these properties at the client level?

Best, Attilio

**Comment by charphi** [comment]
Sure. Here is the use case:
The current system defines ssl&proxy at the application level. It means that if you configure Internet access with it, every component of the application will have that access.
I need to restrict Internet access to the SDMX client only.

**Comment by amattioc** [comment]
Thanks for the explanation.

**Comment by vpinna80** [comment]
@charphi This should be fixed now with 8ea3ccd.

**Comment by charphi** [comment]
Indeed, I've just tested and it works properly.

**Pull request merged**
