### PR TITLE
ABS wildcard

### LINKED ISSUE #19: ABS wildcard white space  error
works:
 tts <-  getSDMX('ABS', 'CPI.1.50.10001.10.Q') 
 names(tts)
[1] "CPI.1.50.10001.10.Q"

fails:
 tts <-  getSDMX('ABS', 'CPI.1.*.10001.10.Q') 
Dec 12, 2014 2:10:41 PM it.bankitalia.reri.sia.sdmx.client.custom.RestSdmx20Client getTimeSeries
SEVERE: Exception caught parsing results from call to provider ABS
Error in .jcall("RJavaTools", "Ljava/lang/Object;", "invokeMethod", cl,  : 
  it.bankitalia.reri.sia.util.SdmxException: Exception. Class: javax.xml.stream.XMLStreamException .Message: ParseError at [row,col]:[1,63]
Message: White spaces are required between publicId and systemId.

### PR DESCRIPTION
**Pull request by charphi**
Should fix #19

### CODE REVIEW

**Comment by amattioc** [comment]
Nice fix. Thanks.

**Comment by charphi** [comment]
It seems that I forgot the imports in ABS.

**Comment by amattioc** [comment]
No problem, I already fixed it... :-)

**Comment by charphi** [comment]
Thanks.

**Pull request merged**
